spring:
  config:
    import: application-secret.yml
  datasource:
    url: ${secret.db.url}
    username: ${secret.db.username}
    password: ${secret.db.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 3000
  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
      map-underscore-to-camel-case: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  data:
    redis:
      host: localhost       # Redis 서버 주소 (로컬 개발환경용)
      port: 6379            # 기본 포트
vworld:
  api:
    key: ${secret.vworld.api-key}
    base-url: https://api.vworld.kr/ned/data/getEBBrokerInfo
